/**
 * @addtogroup examplesdcpsHelloWorldisocpp
 */
/** @{*/
/** @file */

module HelloWorldData
{
   struct Msg
   {
      /** User ID */
      long userID;
      /**  message */
      string message;
      sequence<long,10> X;
   };
   #pragma keylist Msg userID
};

/** @}*/
